### ISSUE TITLE
Question: is the isolate killed after usage?

### ISSUE THREAD

**Issue by DarkHeros09** [chmoore889/isolate_json#2]
Hi

First of all thank you for creating this package,it really makes it easy to use the isolates for json encoding/decoding without the boilerplate.
Can you please confirm that the isolate is killed after decoding the json?
i reviewed your code, and i can't find isolate.kill() anywhere.

**Comment by chmoore889** [comment]
The package does not automatically kill the isolate after decoding the JSON. The purpose of the package is to provide a long-lived isolate for applications that require lots of JSON encoding/decoding and remove the repetitive spawning/killing of isolates with Flutter's `compute`. Therefore, the automatic disposal you mention goes against my intent with making this package. If you want this behavior to maybe be an option that can be configured, feel free to make a PR.

This did bring to my attention that there is no way to destroy the isolate manually, so I've added that in the latest commit and release on pub.dev.

**Comment by DarkHeros09** [comment]
Thank you for your response / insight, this package is definitely a hidden gem.

Thank you for making it.
